import {atob} from "buffer";

type ResourcesID = {
    id: number;
}

const data: Map<number, string> = new Map<number, string>();

function decode(data: string): string {
    if (typeof atob == "undefined") {
        if (typeof Buffer == "undefined") {
            throw "Cannot decode resources no atop and no Buffer class declared";
        } else {
            return Buffer.from(data, "base64").toString("utf-8");
        }
    } else {
        return atob(data);
    }
}

export function load_resources(id: ResourcesID): string {
    if (data.has(id.id)) {
        return decode(<string>data.get(id.id));
    }
    throw "Resources not declared";
}

export function has_resources(id: ResourcesID): boolean {
    return data.has(id.id);
}


export const R: {
    git: {
        release_yml: ResourcesID
    },
    templates: {
        ts_config_json: ResourcesID
    },
    wrapper: {
        bundler_js: ResourcesID,
        res_ts: ResourcesID
    }
} = {
    git: {
        release_yml: {
            id: 0
        }
    },
    templates: {
        ts_config_json: {
            id: 1
        }
    },
    wrapper: {
        bundler_js: {
            id: 2
        },
        res_ts: {
            id: 3
        }
    }
};

data.set(R.git.release_yml.id, "bmFtZTogUmVsZWFzZQ0KDQpvbjoNCiAgcHVzaDoNCiAgICB0YWdzOg0KICAgICAgLSAiKiINCg0Kam9iczoNCiAgYnVpbGQ6DQogICAgbmFtZTogQnVpbGQNCiAgICBydW5zLW9uOiB3aW5kb3dzLWxhdGVzdA0KICAgIHN0ZXBzOg0KICAgICAgLSB1c2VzOiBhY3Rpb25zL2NoZWNrb3V0QHYzDQoNCiAgICAgIC0gbmFtZTogQ3JlYXRlIHJlbGVhc2UgcGFja2FnZQ0KICAgICAgICB1c2VzOiBhY3Rpb25zL3NldHVwLW5vZGVAdjMNCiAgICAgICAgd2l0aDoNCiAgICAgICAgICBub2RlX3ZlcnNpb246IDE2LngNCiAgICAgIC0gcnVuOiBucG0gaW5zdGFsbCAtLWdsb2JhbCB0eXBlc2NyaXB0DQogICAgICAtIHJ1bjogbnBtIGluc3RhbGwgLS1nbG9iYWwgaHR0cHM6Ly9naXRodWIuY29tL0NocmlzdG9waC1Lb3NjaGVsL3RzYi5naXQNCiAgICAgIC0gcnVuOiBucG0gaW5zdGFsbCAtLWdsb2JhbCBodHRwczovL2dpdGh1Yi5jb20vQ2hyaXN0b3BoLUtvc2NoZWwveWFwbS1jbGkuZ2l0DQogICAgICAtIHJ1bjogbnBtIGluc3RhbGwNCiAgICAgIC0gcnVuOiB5YXBtIGluc3RhbGwNCiAgICAgIC0gcnVuOiB0c2IgY29tcGlsZSAtLWxpYiAtLW1pbmlmeQ0KDQogICAgICAtIG5hbWU6IENyZWF0ZSBHaXRIdWIgUmVsZWFzZQ0KICAgICAgICBpZDogY3JlYXRlLXJlbGVhc2UNCiAgICAgICAgdXNlczogYWN0aW9ucy9jcmVhdGUtcmVsZWFzZUB2MQ0KICAgICAgICBlbnY6DQogICAgICAgICAgR0lUSFVCX1RPS0VOOiAke3sgc2VjcmV0cy5HSVRIVUJfVE9LRU4gfX0NCiAgICAgICAgd2l0aDoNCiAgICAgICAgICB0YWdfbmFtZTogJHt7IGdpdGh1Yi5yZWYgfX0NCiAgICAgICAgICByZWxlYXNlX25hbWU6ICR7eyBnaXRodWIucmVmIH19DQogICAgICAtIG5hbWU6IFVwbG9hZCByZWxlYXNlIGFzc2V0cw0KICAgICAgICB1c2VzOiBhY3Rpb25zL3VwbG9hZC1yZWxlYXNlLWFzc2V0QHYxDQogICAgICAgIGVudjoNCiAgICAgICAgICBHSVRIVUJfVE9LRU46ICR7eyBzZWNyZXRzLkdJVEhVQl9UT0tFTiB9fQ0KICAgICAgICB3aXRoOg0KICAgICAgICAgIHVwbG9hZF91cmw6ICR7eyBzdGVwcy5jcmVhdGUtcmVsZWFzZS5vdXRwdXRzLnVwbG9hZF91cmwgfX0NCiAgICAgICAgICBhc3NldF9wYXRoOiAuLyR7eyBnaXRodWIuZXZlbnQucmVwb3NpdG9yeS5uYW1lIH19LSR7eyBnaXRodWIucmVmX25hbWUgfX0ueWFwbS56aXANCiAgICAgICAgICBhc3NldF9uYW1lOiAke3sgZ2l0aHViLmV2ZW50LnJlcG9zaXRvcnkubmFtZSB9fS0ke3sgZ2l0aHViLnJlZl9uYW1lIH19LnlhcG0uemlwDQogICAgICAgICAgYXNzZXRfY29udGVudF90eXBlOiBhcHBsaWNhdGlvbi96aXA=");
data.set(R.templates.ts_config_json.id, "ew0KICAiY29tcGlsZXJPcHRpb25zIjogew0KICAgICJ0YXJnZXQiOiAiZXMyMDIwIiwNCiAgICAibW9kdWxlIjogImVzMjAyMCIsDQogICAgIm1vZHVsZVJlc29sdXRpb24iOiAibm9kZSIsDQogICAgImRlY2xhcmF0aW9uIjogdHJ1ZSwNCiAgICAicmVtb3ZlQ29tbWVudHMiOiB0cnVlLA0KICAgICJvdXREaXIiOiAiYnVpbGQvc3JjIiwNCiAgICAiZGVjbGFyYXRpb25EaXIiOiAiYnVpbGQvaGVhZGVyIiwNCiAgICAicGF0aHMiOiB7DQogICAgICAiQHlhcG0vKiI6IFsiLi9saWIvKiJdDQogICAgfQ0KDQogIH0sDQogICJleGNsdWRlIjogWw0KICAgICJsaWIiLA0KICAgICJhc3NldHMiLA0KICAgICJub2RlX21vZHVsZXMiDQogIF0NCn0=");
data.set(R.wrapper.bundler_js.id, "InVzZSBzdHJpY3QiOw0KDQpjbGFzcyBUU0J1bmRsZXIgew0KICAgIGNvbnN0cnVjdG9yKCkgew0KICAgICAgICB0aGlzLmxvYWRlZCA9IG5ldyBNYXAoKTsNCiAgICAgICAgdGhpcy5tb2R1bGVzID0gbmV3IE1hcCgpOw0KICAgICAgICB0aGlzLmF1dG9sb2FkID0gW107DQogICAgfQ0KDQogICAgZGVmaW5lKG5hbWUsIGltcG9ydHMsIGNiKSB7DQogICAgICAgIHRoaXMubW9kdWxlcy5zZXQobmFtZSwgew0KICAgICAgICAgICAgaW1wb3J0czogaW1wb3J0cywNCiAgICAgICAgICAgIGNiOiBjYg0KICAgICAgICB9KTsNCiAgICB9DQoNCiAgICBsb2FkKG5hbWUpIHsNCiAgICAgICAgdGhpcy5hdXRvbG9hZC5wdXNoKG5hbWUpOw0KICAgIH0NCg0KICAgIGFzeW5jIHN0YXJ0KCkgew0KICAgICAgICBmb3IgKGNvbnN0IGxvYWQgb2YgdGhpcy5hdXRvbG9hZCkgew0KICAgICAgICAgICAgYXdhaXQgdGhpcy5sb2FkUGFja2FnZShsb2FkKTsNCiAgICAgICAgfQ0KICAgIH0NCg0KICAgIGFzeW5jIGxvYWRQYWNrYWdlKG5hbWUpIHsNCiAgICAgICAgaWYgKHRoaXMubW9kdWxlcy5oYXMobmFtZSkpIHsNCiAgICAgICAgICAgIGlmICh0aGlzLmxvYWRlZC5oYXMobmFtZSkpIHsNCiAgICAgICAgICAgICAgICByZXR1cm4gdGhpcy5sb2FkZWQuZ2V0KG5hbWUpOw0KICAgICAgICAgICAgfQ0KICAgICAgICAgICAgbGV0IG1vZCA9IHRoaXMubW9kdWxlcy5nZXQobmFtZSk7DQogICAgICAgICAgICBpZiAobW9kID09IHVuZGVmaW5lZCkgew0KICAgICAgICAgICAgICAgIHJldHVybiB7fTsNCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgIGxldCBfX2ltcG9ydCA9IHt9Ow0KICAgICAgICAgICAgZm9yIChjb25zdCByZXEgb2YgbW9kLmltcG9ydHMpIHsNCiAgICAgICAgICAgICAgICBsZXQgcmVxSW1wb3J0ID0gYXdhaXQgdGhpcy5sb2FkUGFja2FnZShyZXEpOw0KICAgICAgICAgICAgICAgIE9iamVjdC5rZXlzKHJlcUltcG9ydCkuZm9yRWFjaCgodmFsdWUpID0+IHsNCiAgICAgICAgICAgICAgICAgICAgX19pbXBvcnRbdmFsdWVdID0gcmVxSW1wb3J0W3ZhbHVlXTsNCiAgICAgICAgICAgICAgICB9KTsNCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgIGxldCBfX2V4cG9ydCA9IHt9Ow0KICAgICAgICAgICAgYXdhaXQgbW9kLmNiKF9fZXhwb3J0LCBfX2ltcG9ydCk7DQogICAgICAgICAgICB0aGlzLmxvYWRlZC5zZXQobmFtZSwgX19leHBvcnQpOw0KICAgICAgICAgICAgcmV0dXJuIF9fZXhwb3J0Ow0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgdGhyb3cgIk5vIHBhY2thZ2Ugd2l0aCB0aGUgaWQgXCIiICsgbmFtZSArICJcIiBkZWZpbmVkIjsNCiAgICAgICAgfQ0KICAgIH0NCn0NCg0KY29uc3QgYnVuZGxlciA9IG5ldyBUU0J1bmRsZXIoKTsNCg==");
data.set(R.wrapper.res_ts.id, "aW1wb3J0IHthdG9ifSBmcm9tICJidWZmZXIiOw0KDQp0eXBlIFJlc291cmNlc0lEID0gew0KICAgIGlkOiBudW1iZXI7DQp9DQoNCmNvbnN0IGRhdGE6IE1hcDxudW1iZXIsIHN0cmluZz4gPSBuZXcgTWFwPG51bWJlciwgc3RyaW5nPigpOw0KDQpmdW5jdGlvbiBkZWNvZGUoZGF0YTogc3RyaW5nKTogc3RyaW5nIHsNCiAgICBpZiAodHlwZW9mIGF0b2IgPT0gInVuZGVmaW5lZCIpIHsNCiAgICAgICAgaWYgKHR5cGVvZiBCdWZmZXIgPT0gInVuZGVmaW5lZCIpIHsNCiAgICAgICAgICAgIHRocm93ICJDYW5ub3QgZGVjb2RlIHJlc291cmNlcyBubyBhdG9wIGFuZCBubyBCdWZmZXIgY2xhc3MgZGVjbGFyZWQiOw0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgcmV0dXJuIEJ1ZmZlci5mcm9tKGRhdGEsICJiYXNlNjQiKS50b1N0cmluZygidXRmLTgiKTsNCiAgICAgICAgfQ0KICAgIH0gZWxzZSB7DQogICAgICAgIHJldHVybiBhdG9iKGRhdGEpOw0KICAgIH0NCn0NCg0KZXhwb3J0IGZ1bmN0aW9uIGxvYWRfcmVzb3VyY2VzKGlkOiBSZXNvdXJjZXNJRCk6IHN0cmluZyB7DQogICAgaWYgKGRhdGEuaGFzKGlkLmlkKSkgew0KICAgICAgICByZXR1cm4gZGVjb2RlKDxzdHJpbmc+ZGF0YS5nZXQoaWQuaWQpKTsNCiAgICB9DQogICAgdGhyb3cgIlJlc291cmNlcyBub3QgZGVjbGFyZWQiOw0KfQ0KDQpleHBvcnQgZnVuY3Rpb24gaGFzX3Jlc291cmNlcyhpZDogUmVzb3VyY2VzSUQpOiBib29sZWFuIHsNCiAgICByZXR1cm4gZGF0YS5oYXMoaWQuaWQpOw0KfQ0KDQo=");
